# Generated by Django 4.0.6 on 2023-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('date_post', models.DateField(blank=True, null=True)),
                ('short_decsription', models.CharField(max_length=100)),
                ('long_decsription', models.TextField(default='DESC')),
                ('type', models.CharField(choices=[('News', 'News'), ('Blogs', 'Blogs')], default='Blogs', max_length=50)),
                ('most_popular', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('main', models.BooleanField(default=False)),
                ('main2', models.BooleanField(default=False)),
                ('cate', models.CharField(choices=[('ثقافة', 'ثقافة'), ('اقتصاد', 'اقتصاد'), ('رياضة', 'رياضة'), ('صحةوجمال', 'صحةوجمال'), ('تكنولوجيا', 'تكنولوجيا'), ('خبر', 'خبر')], max_length=12)),
            ],
        ),
    ]
