# Generated by Django 4.0.6 on 2023-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='cate',
            field=models.CharField(choices=[('اقتصاد', 'اقتصاد'), ('رياضة', 'رياضة'), ('صحةوجمال', 'صحةوجمال'), ('تكنولوجيا', 'تكنولوجيا'), ('خبر', 'خبر')], max_length=12),
        ),
    ]
